VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Arkusz5"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

Sub fff()
Attribute fff.VB_ProcData.VB_Invoke_Func = "t\n14"
'
'Me.Label.Select
'Selection.Delete
'Me.Label.AutoSize = True
'Me.Label.Font.Size = 16
'Me.Label.Font.Bold = True
'Me.Label.ForeColor = RGB(227, 228, 229)
'ActiveSheet.Shapes("pole tekstowe 2").Visible = True
''
'ActiveSheet.Shapes("pole tekstowe 2").TextFrame.Characters.Text = "nowodworski (mazowieckie)"
'ActiveSheet.Shapes("pole tekstowe 2").TextFrame.AutoSize = True
'ActiveSheet.Shapes("pole tekstowe 2").Fill.Transparency = 0.2

'Me.Label.AutoSize = True
'MsgBox znalezionyZM
'MsgBox lewyPts(1)

'
'Sheets("Powiaty").Rows("58:1048576").Select
'Selection.EntireRow.Hidden = True

'Sheets("Powiaty").Columns("ER:XFD").Select
'Selection.EntireColumn.Hidden = True
'Me.Range("woj").Interior.color = RGB(83, 141, 213)

'ActiveSheet.Shapes.Range(Array("Kraj")).Name = "Kraj"
'ActiveSheet.Shapes.Range(Array("Woj")).Name = "Woj"
'ActiveSheet.Shapes.Range(Array("Powiat")).Name = "Powiat"


End Sub

'Private Sub Worksheet_Change(ByVal Target As Range)
'
'    If powiatZM(1) = "" Then
'
'        Odswiez
'
'    End If
'
'End Sub

